name: shadow_chat
description: A secretive chat app
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"  # Updated to Dart 3.x

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0  # Corrected indentation

flutter:
  uses-material-design: true