// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDISYtshenfaToF-d1cVyJiYEG4o5lBlQI',
    appId: '1:505358154982:web:623e620879435dc5fd8f27',
    messagingSenderId: '505358154982',
    projectId: 'shadowchat-73d0b',
    authDomain: 'shadowchat-73d0b.firebaseapp.com',
    storageBucket: 'shadowchat-73d0b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE_navrMNI6bTNBngEmYD-BtLNztawnLQ',
    appId: '1:505358154982:android:93dc507fb9e778f8fd8f27',
    messagingSenderId: '505358154982',
    projectId: 'shadowchat-73d0b',
    storageBucket: 'shadowchat-73d0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXXol5VHgw1qSh739wKoIs8vFPW24AM3k',
    appId: '1:505358154982:ios:d1a8d568dc252a3dfd8f27',
    messagingSenderId: '505358154982',
    projectId: 'shadowchat-73d0b',
    storageBucket: 'shadowchat-73d0b.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXXol5VHgw1qSh739wKoIs8vFPW24AM3k',
    appId: '1:505358154982:ios:d1a8d568dc252a3dfd8f27',
    messagingSenderId: '505358154982',
    projectId: 'shadowchat-73d0b',
    storageBucket: 'shadowchat-73d0b.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDISYtshenfaToF-d1cVyJiYEG4o5lBlQI',
    appId: '1:505358154982:web:3c0c884e4f69dc34fd8f27',
    messagingSenderId: '505358154982',
    projectId: 'shadowchat-73d0b',
    authDomain: 'shadowchat-73d0b.firebaseapp.com',
    storageBucket: 'shadowchat-73d0b.firebasestorage.app',
  );
}
